# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9895e163c9bd1992b8dab219f050e7c251ca7450aaead4c530c448ef029bebf0114215c5e875c479a6162af92a986bcc4f616d9516eeb3a29bf9d3310aaeea7

test:
  secret_key_base: b437bb6f6c1a7f85359b44a33fa7ec689610f19d74e48691ea5fad90062684133fd6af10150cd32ae120d800ed678867392af3aecfaaacf953eecc6e2482fcff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
